### PR TITLE
Implement argparse

### PR DESCRIPTION
**Pull request by alanyee**
-Implement argparse
-Remove unnecessary print calls that cause unnecessary overhead
-List comprehensions

### CODE REVIEW

**Comment by SammyHass** [comment]
No need for argparse. Additional dependencies are not required.

**Comment by stewartmcgown** [comment]
I'm not actually against argparse, might make things easier later on.

**Comment by PeterTheHe** [comment]
argparse is portable and pretty much standard at this point. +1 for increased maintainability.

On a somewhat unrelated note, verbosity flags for easier debugging?

**Comment by alanyee** [comment]
@PeterTheHe I can make secondary shorter flags. It is easy to do; I just wanted to keep my changes roughly minimal in case this PR was rejected for some reason.

@SammyHass I would say there is a need for argparse especially since the help message is not up-to-date, makes adding new flags/features easier, allows the same uds process to do multiple different tasks, and besides, argparse is in the python standard library.

**Comment by SammyHass** [comment]
Sure, @PeterTheHe and @stewartmcgown are the gods here. Their opinions are more relevant than mine. Sorry guys and sorry @alanyee for being harsh. I will review your code now.

Sorry again

**Comment by SammyHass** [comment]
Will also start on contribution guidelines at some point so I can't be as much of a dick.

**Pull request merged**
