### PR TITLE
Organize Files by Path

### PR DESCRIPTION
**Pull request by ghost**
...

### CODE REVIEW

**Comment by stewartmcgown** [comment]
This should be optional, via a flag imo

**Review by sammyhass — CHANGES_REQUESTED** [review]
@stewartmcgown requested some changes, thanks https://github.com/stewartmcgown/uds/pull/104#issuecomment-728855875

**Review by ghost — COMMENTED** [review]
...

**Comment by BluelyTASer** [comment]
> This should be optional, via a flag imo

I can't be able to implement as a flag, I'm still intermediate at coding python.

**Pull request closed without merging**
